### ISSUE TITLE
Better in-app help info & documentation

### ISSUE THREAD

**Issue by matro** [buildinspace/peru#100]
__The problem__: differences in `master`'s `README` as seen on Github and behavior of the `pip`-installed version of the program. "Why can't I do this thing the docs say I can?" (like #97). Having to bail out to a browser and look up this project is rough and tedious for quick-reference needs.

__A solution__: have more and more thorough documentation built and shipped with the `pip`-installed package. `man peru` would be a really good command to be able to run. Deeper and more fleshed-out docs for `peru help` (and `peru help $cmd` or `peru $cmd help`) would be similarly useful.

No idea how easy/hard this would be though, but hopefully it's something that could be handled by the building/packaging/installing process? And being able to use the project's `README` or other canonical "this is how stuff works" file(s) as the source would be wise, too... maintaining disparate copies of documentation is no fun.

**Comment by matro** [comment]
I'd definitely be willing to try to help with this, though I've got pretty much zero Python experience. Aim me at "the place where the docs are derived from" and I can see what I can do?

**Comment by oconnor663** [comment]
Woohoo issue 100! (Is having a lot of issues a good thing? Maybe I should celebrate when we *fix* 100 issues :smile:)

Peru uses [docopt](http://docopt.org/) for command line parsing, which actually uses the docstring itself to figure out how to parse arguments, so it should be pretty easy for us to write a nice git-style sub-command help thing without repeating ourselves. There's actually [an example of just that](https://github.com/docopt/docopt#subparsers-multi-level-help-and-huge-applications-like-git) in the docopt repo.

Right now our docopt string is [a big blob in `peru/main.py`](https://github.com/buildinspace/peru/blob/d935d409366f5b7738b367057c6eee04c1e4cd1d/peru/main.py#L17-40), with all the sub-commands handled in one parsing step. As they do in that example, we'll probably want to split that into separate files somehow, and I bet we'll want to use plain text files to hold the docstrings. Writing those text files is definitely something that you could help with without needing to write Python code, though you'd need to be careful to stick to the way docopt expresses things. Maybe take a look at the docopt instructions and see how much sense those make?

I don't know of a widely-used way to generate man pages from docstrings, or to generate man pages and docstrings from some other thing. It seems like using `pip` to install man pages is a little nonstandard too. We might want to punt on man pages then, unless you know of a project that does a really clean job of it.

In other news, #97 was totally my fault, and in the future I don't plan to let `README.md` get out of sync with the latest release. We can probably create a `readme-next` branch or something to hold changes that haven't launched yet.

**Comment by matro** [comment]
Yeah, I was pretty tickled to see "100" happen here. For my very first public Github issue, even!

I'll see if I can learn me some docopt, and try to get together something for a pull request.

I'll also see if I can find anything promising for getting manfiles built, but meh; it might be the easiest way to get Peru's docs into http://kapeli.com/dash (which is the first place I go for docs most of the time), but that'd just icing on the cake. If nothing looks promising, punting the `man` makes lots of sense.

**Comment by matro** [comment]
And no worries about #97. It happens. Ironically, I tend to have more trust in projects with reasonable numbers of issues than the ones that are ghost towns. Even better (and more ironically?) having to trawl through the issues here to find things not readily apparent from the docs, and discovering things like the nuances of `reup`... it's been very telling, in the good way. #97 might've even been what tipped me over the edge into "heck, let's brain-dump into some issues and see what happens" territory this evening, I don't remember.

I say, celebrate on _both_ the opening and closing of The Big 100!

**Comment by oconnor663** [comment]
I have a diff up for subcommand help: https://phabricator.buildinspace.com/D209

**Comment by oconnor663** [comment]
This shipped with version 0.2.2. You can now do every permutation of

    peru [help | --help | -h] <command> [--help | -h]
