### ISSUE TITLE
`peru sync --ignore-overrides`

### ISSUE THREAD

**Issue by MatthewEppelsheimer** [buildinspace/peru#139]
As a developer with many overrides for local change testing, I need to delete them all when it's time to create an actual build, and then re-add them after. It would be nice to add a flag that … well, overrides my overrides at `peru sync` time.

**Comment by oconnor663** [comment]
That's a good idea. One workaround you can use in the short term is to move away the directory `.peru/overrides`, and then move it back when you want to restore your overrides.

**Comment by MatthewEppelsheimer** [comment]
:+1: That's what we're doing for now.

**Comment by oconnor663** [comment]
Just pushed https://github.com/buildinspace/peru/commit/b14dedf21f581e8079b77189a99f6a49c014d8b8. Could you please try the new `--nooverrides` flag on your end and let me know how it works?

I'm calling it `--nooverrides` for consistency with `--nosync`, but if anyone feels very strongly about whether an extra hyphen there should be in there, let me know. @olson-sean-k?

**Comment by oconnor663** [comment]
Eh, I changed my mind about the dash: https://github.com/buildinspace/peru/commit/5fd42e4481046b86e61c1828b86026b3cd0d62aa

Now it's `--no-overrides`, and I've renamed `--no-sync` to match. I don't expect anyone actually used `---nosync` in practice, so I'm not too worried about breakage. Better to do it now than after 1.0...

**Comment by MatthewEppelsheimer** [comment]
Sorry I haven't been able to get you feedback yet. It's on my todo list, but the list is long. :smile:

**Comment by oconnor663** [comment]
No worries, I'm like 75% sure the feature works :p

**Comment by MatthewEppelsheimer** [comment]
Finally got around to using this, and can confirm working.

**Comment by oconnor663** [comment]
Woo!
