### ISSUE TITLE
Feature request: parameterized urls for rules

### ISSUE THREAD

**Issue by kergoth** [buildinspace/peru#148]
I have a case where I need to do a curl fetch of quite a few individual files, given the same base url. I think it'd be useful for cases like this if a rule could either replace parameters in the url, or append to the url, rather than having to copy/paste the block around.

**Comment by oconnor663** [comment]
Would it work to generate your `peru.yaml` file from a script? That's usually been my suggestion for files that have a lot of internal repetition. YAML itself also has some features for copying other parts of a file, though I don't think any of that works inside of a string.

**Comment by kergoth** [comment]
That's a good point, there are plenty of templating mechanisms around I could use as is at a level above peru, or home-roll something. Thanks for the suggestion, I'll try that out.

**Comment by oconnor663** [comment]
Please let me know how it goes. My hope is that we can keep peru pretty lightweight, but I won't really know until people run up against these use cases.
