### ISSUE TITLE
coalesce errors while there are running jobs

### ISSUE THREAD

**Issue by oconnor663** [buildinspace/peru#162]
This is close to working, though I need to rework the way exceptions get aggregated according to @olson-sean-k's suggestion: https://github.com/buildinspace/peru/tree/coalesce

There are two conflicting scenarios that we need to get right:

- When I have long running jobs, I don't want to wait until the very end to find out that there was an error. It would be nice to get some sort of feedback immediately.
- When there's nothing else to wait for, and peru is just going to print my error and exit, I don't want it to get printed twice.

Here's what we want to do:

- Gather all caught exceptions at the fork point, and reraise a container exception type that includes all of them in a list. Tests looking for a specific exception type will need to traverse that list, but will otherwise still work. It probably makes sense for nested gathers to flatten each other. For example, if there's an error inside a recursive module, we want to avoid something like `GatherError(GatherError(RealError))` by unpacking the inner gather.
- Have gather be a `PrintableError` that displays all of its contained error messages, and rely on the existing error printing in `main`. It would be nice if it was aware of verbosity somehow, for stack traces.
- Use the fancy display to show error information while jobs are still running. This will probably involve holding onto display handles after releasing job locks somehow. Maybe even add support for red text in the display...

**Comment by olson-sean-k** [comment]
I'm not convinced that displaying errors early for long running jobs is worth the trouble. Users don't have many options beyond Ctrl+C if they encounter an error in a long running sync, for example. Instead, maybe we can provide a `--fail-fast` flag to prevent newly scheduled co-routines from doing any work. This could be handy to avoid long waits if errors occur, while also avoiding manual babysitting.

If we don't worry about displaying errors right when they happen, then we only need to focus on aggregating and printing exceptions as you've outlined (and maybe failing fast).

**Comment by oconnor663** [comment]
My only data point is that when I'm waiting several seconds for a sync to finish, with no feedback about whether it's still actually making progress or whether it's already failed, it feels like torture :)

**Comment by oconnor663** [comment]
Ok, I've landed the error coalescing branch. I haven't gotten to anything with early error reporting, and I'm starting to agree that it might not be worth the trouble. But plugin errors are _much_ cleaner now :)

Before (note that only one of the real errors is displayed at all):

```
┌ oh-my-zsh: Cloning into bare repository '/home/jacko/tmp/dotfiles/.peru/cache/plugins/git/39fd4e28db80
└ vim-coffee: Receiving objects:  78% (2149/2754), 348.01 KiB | 111.00 KiB/s
In target "vim-coffee":
  git plugin exited with error code 1.
  Fields:
      rev: 32fe889b8cafd3a4921ef8e6485156453ff58c42
      url: https://github.com/kchmck/vim-coffee-script
  Output:
  git clone https://github.com/kchmck/vim-coffee-script
  Cloning into bare repository '/home/jacko/tmp/dotfiles/.peru/cache/plugins/git/b15648bd1f5049b53b5a5e2864b7824a7f3476be/cf9859623fddf70dfe893d2d53d463b3638414c4'...
  remote: Counting objects: 2754, done.
  error: object 82f4e81921a9d8f8aac23746341e8ec860a3e302: zeroPaddedFilemode: contains zero-padded file modes
  fatal: Error in object
  fatal: index-pack failed
  Traceback (most recent call last):
    File "/home/jacko/peru/peru/resources/plugins/git/git_plugin.py", line 147, in <module>
      plugin_sync()
    File "/home/jacko/peru/peru/resources/plugins/git/git_plugin.py", line 134, in plugin_sync
      checkout_tree(URL, REV, os.environ['PERU_SYNC_DEST'])
    File "/home/jacko/peru/peru/resources/plugins/git/git_plugin.py", line 93, in checkout_tree
      repo_path = clone_and_maybe_print(url)
    File "/home/jacko/peru/peru/resources/plugins/git/git_plugin.py", line 67, in clone_and_maybe_print
      return clone_if_needed(url)
    File "/home/jacko/peru/peru/resources/plugins/git/git_plugin.py", line 53, in clone_if_needed
      git('clone', '--mirror', '--progress', url, repo_path)
    File "/home/jacko/peru/peru/resources/plugins/git/git_plugin.py", line 41, in git
      output))
  RuntimeError: Command exited with error code 128:
  $ git clone --mirror --progress https://github.com/kchmck/vim-coffee-script /home/jacko/tmp/dotfiles/.peru/cache/plugins/git/b15648bd1f5049b53b5a5e2864b7824a7f3476be/cf9859623fddf70dfe893d2d53d463b3638414c4
  None
Exception ignored in: <bound method BaseSubprocessTransport.__del__ of <_UnixSubprocessTransport closed pid=12071 running stdout=<_UnixReadPipeTransport closing fd=7 open>>>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/base_subprocess.py", line 126, in __del__
  File "/usr/lib/python3.5/asyncio/base_subprocess.py", line 101, in close
  File "/usr/lib/python3.5/asyncio/unix_events.py", line 376, in close
  File "/usr/lib/python3.5/asyncio/unix_events.py", line 404, in _close
  File "/usr/lib/python3.5/asyncio/base_events.py", line 497, in call_soon
  File "/usr/lib/python3.5/asyncio/base_events.py", line 506, in _call_soon
  File "/usr/lib/python3.5/asyncio/base_events.py", line 334, in _check_closed
RuntimeError: Event loop is closed
Task was destroyed but it is pending!
task: <Task pending coro=<get_tree() running at /home/jacko/peru/peru/imports.py:42> wait_for=<Future pen
```

After (both are displayed):

```
In target "vim-coffee":
  git clone https://github.com/kchmck/vim-coffee-script
  Cloning into bare repository '/home/jacko/tmp/dotfiles/.peru/cache/plugins/git/b15648bd1f5049b53b5a5e2864b7824a7f3476be/cf9859623fddf70dfe893d2d53d463b3638414c4'...
  remote: Counting objects: 2754, done.        
  error: object 82f4e81921a9d8f8aac23746341e8ec860a3e302: zeroPaddedFilemode: contains zero-padded file modes
  fatal: Error in object
  fatal: index-pack failed

In target "oh-my-zsh":
  git clone https://github.com/robbyrussell/oh-my-zsh
  Cloning into bare repository '/home/jacko/tmp/dotfiles/.peru/cache/plugins/git/39fd4e28db807b33a999697f17567b8bfb188e7e/7295ef8cba123f36de8fd77ac096feb478c7d208'...
  remote: Counting objects: 54551, done.        
  remote: Compressing objects: 100% (22/22), done.        
  error: object 2b7227859263b6aabcc28355b0b994995b7148b6: zeroPaddedFilemode: contains zero-padded file modes
  fatal: Error in object
  fatal: index-pack failed
```

**Comment by oconnor663** [comment]
Forking off the fancy display stuff as https://github.com/buildinspace/peru/issues/164.
