### ISSUE TITLE
"Syntax error: invalid syntax" after changing a repo URL on Windows

### ISSUE THREAD

**Issue by edbrannin** [buildinspace/peru#176]
## Steps to reproduce:

1. `peru sync` successfully
2. Change the URL of a git module, because vim-snipmate has a new home now.
3. `peru sync`

## Expected result:

That directory comes from a different remote now.

## Observed result:

```
$ peru sync
In target "snipmate-vim":
    File "C:\Python36\lib\site-packages\peru-1.1.0-py3.6.egg\peru\resources\plugins\git\git_plugin.py", line 20
      def git(*args, git_dir=None, capture_output=False):
                           ^
  SyntaxError: invalid syntax
```

## Notes

* Reverting the URL makes the problem go away, except I can't update snipmate. :)
* Adding a new module also doesn't seem to work.  It's possible that something broke about my setup here, but I'm not sure don't know how to debug from here.

**Comment by oconnor663** [comment]
Sorry for the radio silence on this one. I'm going to release your previous fix now, and I'll get to this one later this week.

**Comment by oconnor663** [comment]
What's happening here is that the plugin is getting launched with Python 2 instead of Python 3. If you recently installed Python 2 after Python 3, that's probably what caused this. That said, the specific of how a script on Windows selects the right Python version are [kind of complicated](https://docs.python.org/3.6/using/windows.html#shebang-lines).

Rerunning the Python 3 installer might fix the issue? And it might be important to install the "Python launcher for Windows" if you didn't before?

**Comment by edbrannin** [comment]
I was wondering if it was a Python2-related issue, and come to think of it I _had_ reinstalled Python2 after initially running peru.

Right now there doesn't seem to be a workaround beyond "Reinstall Python3".  Were it possible to run peru as a module, I could have run it with `py -3 -m peru sync`.

**Comment by edbrannin** [comment]
1. The "Python launcher for Windows" is installed automatically with Python3, so that's not needed -- it just didn't help me run peru because of the run-as-module thing.
2. Would it be feasible to make the [shebang](https://docs.python.org/3.6/using/windows.html#from-a-script) line `#! python3` on Windows?

**Comment by oconnor663** [comment]
You actually can run it as a module. Try `py -3 -m peru.main sync`.

I think `#! /usr/bin/env python3` is the most correct thing on Unix, and the docs claim that the Windows launcher knows how to handle it. Are you sure the launcher is what's being invoked? It might be that the Python 2 interpreter overwrote the launcher's reg keys?

**Comment by edbrannin** [comment]
Oh, good to know!  I never thought to add a `.main` to the end.  (Might you accept a PR to make the top-level module to invoke main, if run directly?  That would be less surprising.)

"Python2 overwrote the file association" is a plausible explanation.  Sadly, I've had to replace my hard drive _again_ (yay refurb!) after reporting this issue so I'm not super-inclined to intentionally reproduce the issue.
