### ISSUE TITLE
cp modules cannot be updated / reupped

### ISSUE THREAD

**Issue by wshallum** [buildinspace/peru#188]
Modules with cp cannot be updated with peru sync even if the source files have changed.

Not sure if this is intended or not.

To reproduce:

Create `peru.yaml`:

```
$ cat peru.yaml 
imports:
  m: dst/

cp module m:
  path: src/
$ cat src/file
a
$ peru sync
$ cat dst/file 
a
```

Change the file then sync, no change.

```
$ echo b > src/file
$ peru sync
$ cat dst/file
a
```

Clean then sync, still uses initial file.

```
$ peru clean
$ cat dst/file
cat: dst/file: No such file or directory
$ peru sync
$ cat dst/file
a
```

Running reup on the module does not work because cp does not support reup.

**Comment by oconnor663** [comment]
You could use the `--no-cache` flag to tell peru to re-fetch the directory. In a way this is similar to how git behaves when you don't have a `rev` specified. The first time you `sync`, it'll talk to the network and fetch the current git `HEAD`. But on subsequent syncs, it won't re-fetch, unless you bust the cache.

That said, `cp` is an undocumented plugin that only exists for testing. Could you say more about what you're using it for? There's a good chance another approach would be better.

**Comment by wshallum** [comment]
I'm using it to patch (replace) some files that I exclude from the other modules with some files that are in my source directory. Right now what I do is rename/move the original files to `*.orig` then run an additional script that runs patch to create the patched files.

**Comment by oconnor663** [comment]
Have you looked at the `override` command? It's only briefly described in the docs, but it might be exactly what you need here.

**Comment by wshallum** [comment]
I have looked at override, but that replaces the whole module instead of just some files.

**Comment by oconnor663** [comment]
Ah I think I understand the workflow you were describing better. Have you thought about checking the replacement files directly into your project, instead of having peru fetch them? If you're already blacklisting them from other modules, that should work. (Peru doesn't mind that you've checked in directories that it's fetching. It only errors out if the files themselves have the same name.)
