### ISSUE TITLE
pip install yields error "AttributeError: 'module' object has no attribute 'ScriptWriter'"

### ISSUE THREAD

**Issue by dheater** [buildinspace/peru#189]
Peru fails to install:
Python 2.7.5
pip 9.0.3
CentOS Linux release 7.4.1708 (Core) 

```
$ pip install peru
Collecting peru
  Using cached peru-1.1.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-kB42bl/peru/setup.py", line 8, in <module>
        import fastentrypoints
      File "fastentrypoints.py", line 77, in <module>
        easy_install.ScriptWriter.get_args = get_args
    AttributeError: 'module' object has no attribute 'ScriptWriter'
```

**Comment by dheater** [comment]
Works with:
Python 3.4.5
pip3 8.1.2
CentOS Linux release 7.4.1708 (Core)

**Comment by oconnor663** [comment]
Peru only works with Python 3. If you manage to get it installed, you'll find that it causes syntax errors under Python 2. We felt that because peru is a standalone program and not a library, there wasn't much value in making it 2-compatible.

**Comment by dheater** [comment]
Thanks for the quick reply. Sorry I skimmed the instructions and didn't catch the note

> It requires python (3.3 or later)

**Comment by oconnor663** [comment]
No worries. I'm actually kind of surprised that `pip2` is able to find `peru`. Maybe I didn't put the right version metadata in `setup.py`?
