### ISSUE TITLE
feature_request(speed): first launch

### ISSUE THREAD

**Issue by Kristinita** [buildinspace/peru#204]
### 1. Summary

It would be nice, if first launch speed will more quickly.

### 2. Example

[**Pelican**](https://blog.getpelican.com/) haven't plugin manager → users needs install plugins from [**GitHub repository folders**](https://github.com/getpelican/pelican-plugins). For example, I want to load [**`sitemap` plugin**](https://github.com/getpelican/pelican-plugins/tree/master/sitemap) via peru.

+ `peru.yaml`:

```yaml
imports:
  sitemap: plugins/

git module sitemap:
  url: https://github.com/getpelican/pelican-plugins
  pick: sitemap
```

+ output (I use [**ptime**](https://superuser.com/a/397402/572069)):

```text
D:\…Repositories\SashaPythonista>ptime peru sync

ptime 1.0 for Win32, Freeware - http://www.pc-tools.net/
Copyright(C) 2002, Jem Berkes <jberkes@pc-tools.net>

=== peru sync ===

Execution time: 751.484 s
```

12,5 minutes for 3 small files downloading — it's a lot.

I want to use peru for continuous integration. If `.peru` folder in `.gitignore`, continuous integration build time increases significantly.

#### 3.1. git clone depth

`depth: 1` option as described **#183**. User can add to `peru.yaml`:

```yaml
git:
  depth: 1
```

For example, this behavior realized in:

+ [**Travis CI**](https://docs.travis-ci.com/user/customizing-the-build/#git-clone-depth)
+ [**AppVeyor**](https://www.appveyor.com/docs/how-to/repository-shallow-clone/#setting-depth-of-git-clone-command)

#### 3.2. download specific folders

Third-party tools can download specific folders from GitHub:

+ [**Download a single folder or directory from a GitHub repo**](https://stackoverflow.com/q/7106012/5951529)
+ [**Allow downloading only a directory**](https://github.com/dear-github/dear-github/issues/95)

[**githubdl**](http://githubdl.seso.io/) is Python tool. Problems:

1. [**githubdl doesn't support submodules at the time**](https://github.com/wilvk/githubdl/issues/10)
1. [**obtaining GitHub token required**](http://githubdl.seso.io/)

Thanks.

**Comment by oconnor663** [comment]
Apologies for leaving your issues unanswered for so long. Somehow I missed the GitHub emails back in March.

You linked to issue #183, which indeed describes some of the problems with using git's `--depth` flag. The main worry is that it would make peru's primary use case slower. Please comment there if you have any ideas for solving that problem.

In this specific case, it looks like cloning `pelican-plugins` is taking a very long time because it has a lot of git submodules, and by default peru also clones all of those. You should see a big improvement if you add this flag to your module definition:

    submodules: false

Please let me know if that helps.

**Comment by Kristinita** [comment]
**Status: CONFIRMED** :heavy_check_mark:

### 1. Behavior

#### 1.1. Before

**If**:

```yaml
imports:
  sitemap: plugins/

git module sitemap:
  url: https://github.com/getpelican/pelican-plugins
  pick: sitemap
```

Result:

```text
D:\SashaDemoRepositories\SashaPelicanDebugging>ptime peru sync

ptime 1.0 for Win32, Freeware - http://www.pc-tools.net/
Copyright(C) 2002, Jem Berkes <jberkes@pc-tools.net>

=== peru sync ===

Execution time: 879.558 s
```

#### 1.2. After

**Else**:

```diff
git module sitemap:
  url: https://github.com/getpelican/pelican-plugins
  pick: sitemap
+ submodules: false
```

I removed `.peru` and `sitemap` folders → I ran `peru sync` again:

```text
D:\SashaDemoRepositories\SashaPelicanDebugging>ptime peru sync

ptime 1.0 for Win32, Freeware - http://www.pc-tools.net/
Copyright(C) 2002, Jem Berkes <jberkes@pc-tools.net>

=== peru sync ===

Execution time: 152.112 s
```

The behavior is reproduced:

```text
D:\SashaDemoRepositories\SashaPelicanDebugging>ptime peru sync

ptime 1.0 for Win32, Freeware - http://www.pc-tools.net/
Copyright(C) 2002, Jem Berkes <jberkes@pc-tools.net>

=== peru sync ===

Execution time: 151.406 s
```

### 2. Environment

1. Windows 10.0.18363 Pro N for Workstations 64-bit EN
1. Python 3.8.6
1. Peru 1.2.0

### 3. Note

It would be nice download files in my example in less than 2 and a half minutes. Looking forward to a successful solution **#183**.

Thanks.
