### ISSUE TITLE
JavaScript version to embed in Electron？

### ISSUE THREAD

**Issue by linonetwo** [buildinspace/peru#212]
I'd like to include this freature to my electron app, but python is not easy to port with electron app, so do you know there are any JS version of this kind? Thanks.

**Comment by oconnor663** [comment]
Yes take a look at https://github.com/connor4312/blake3.

**Comment by oconnor663** [comment]
Woops so sorry. I spend a lot of time yesterday working on that other project, and I just clicked the github email without looking at what project it was from.

**Comment by oconnor663** [comment]
To be clear, do you want to use peru to _develop_ your electron app, or do you want the electron app to _run_ peru for the end user?

**Comment by linonetwo** [comment]
I hope electron app to run peru for the end user,

A tiddlywiki plugin mentions peru https://github.com/sobjornstad/TiddlyRemember#building-from-source , and I'm developing a electron wrapper for tiddlywiki, hoping that I can make tiddlywiki plugin upgrade more easy to use with GUI wrapper.

**Comment by oconnor663** [comment]
Gotcha. My thinking is, it would probably be easier to run peru during development, and then package the files that peru fetches for you? But I'm not sure how these projects work.

In any case, to answer your original question, no there's no way to run peru without Python today.

**Comment by linonetwo** [comment]
Ok, I'll consider bringing a python with my electron if I am going to use peru.

Actually I want it to run in app's user's computer rather than my computer.
Thank you for your explaination.
