### ISSUE TITLE
Create a Contributing File

### ISSUE THREAD

**Issue by felipefoz** [buildinspace/peru#215]
Hey, it's me again.
As I was starting to have some fun with the code and thinking about contributing, I've missed a file detailing steps for developing the code. 
As a matter of fact I have some experience, but still I learned a lots of things along the way.
Maybe a file with all these steps could be a way to go.
Are you up for accepting a contributing file?
I might start writing as I am probably working on a new contribution.
Cheers,

**Comment by oconnor663** [comment]
Sure, that sounds like a great idea.
