### ISSUE TITLE
If my libs are in gitlab under SSH access, Peru can't clone

### ISSUE THREAD

**Issue by ElleNearMello** [buildinspace/peru#249]
```
 fatal: Could not read from remote repository.

  Please make sure you have the correct access rights
  and the repository exists.
```

Add documentation about where to store keys and info for access. I normally use TortoiseGit with Windows.
Peru's code doesnt seem to find my private key or access configuration automatically.

**Comment by oconnor663** [comment]
Peru is going to shell out to whatever `git` binary is at the front of your `$PATH`/`%PATH%`. If you open a terminal and run `git clone ...`, are you able to clone your repo? If not, fixing your terminal `git` environment should fix Peru.

**Comment by ElleNearMello** [comment]
thanks, I fixed. No issue by Peru code
