### ISSUE TITLE
make it possible to keep .peru under .git

### ISSUE THREAD

**Issue by oconnor663** [buildinspace/peru#28]
It's often convenient to store metadata inside the `.git` directory. See http://tbaggery.com/2011/08/08/effortless-ctags-with-git.html. We should make it easy to move `.peru` to `.git/peru`, without breaking the ability to run peru commands outside the project root. Probably some modification to how we handle `$PERU_DIR` or some new variable.

**Comment by oconnor663** [comment]
Closed in favor of #108.

**Comment by olson-sean-k** [comment]
Really closing in favor of #108. :-)
