### ISSUE TITLE
Add `peru init`

### ISSUE THREAD

**Issue by huyderman** [buildinspace/peru#65]
I find it very convenient when command line tools have a `init` command, even if it's just adding a barebones or example config file.

**Comment by timdp** [comment]
You could extend the concept to support init templates, such as a template for single-page Web apps that pulls in Angular and Bootstrap. Which makes me think that there should be peru generators for [yeoman](http://yeoman.io/), which could in turn even replace `peru init` altogether.

**Comment by olson-sean-k** [comment]
I played with this a bit, and indeed used templates to generate example `peru.yaml` files. It seems to me that user templates would be the natural thing to do. I'm a bit worried something like this might be overkill though.

List available templates:
```
$ peru template
default
web
```
Deploy the "web" template and (dubiously) generate ignore data for git:
```
$ peru init --template=web --ignore=git
$ ls -a
./  ../  peru.yaml  .gitignore
```

**Comment by mitchtbaum** [comment]
I could see this making a lot of sense:

Let's say a project, such as [Pelican](https://github.com/getpelican/pelican), indicated that it expected users to use Peru for plugins and themes, going into /plugins and /themes respectively.  Then, `peru init` could make those folders and establish a `peru.yaml` file with imports to those directories, based on its template.

Then, `peru add plugin minify` could add to your `peru.yaml` file this module to be imported as a plugin.  To make this very smooth, it would be great if Pelican could also provide a sort of manifest/catalog from which Peru could lookup this minify plugin's repo url.

**Comment by oconnor663** [comment]
I think I agree with @timdp: There's no particular reason peru could do a better job than an external tool at setting up a project template for you. And tools like yeoman.io seem to have a ton of neat features already that peru wouldn't really want to take on.

If there was a way we could make a lot of assumptions about what our users want, or if there was a lot of redundant information in the `peru.yaml` file we could fill out, then it might make sense to support some kind of init ourselves. But we try to be pretty agnostic about the kinds of projects peru ends up in, and redundancies in `peru.yaml` are hopefully design mistakes that we can fix. So I'm going to close this one for now.
