### ISSUE TITLE
Do you have plan to support nested repos and 'reup' for branch or those features are already there? 

### ISSUE THREAD

**Issue by enzochiau** [buildinspace/peru#74]
I am not sure if you already have or plan to support these features:

1. Nested repos with peru managed modules.
2. update to a branch when do 'reup': For example I need to track a module's release branches instead of 'master'.

**Comment by oconnor663** [comment]
1. Yep! This is the main new feature we're working on right now. Look for it within the next month or so, as peru 0.2. (Issue #29) Recursive repos will work a lot like recursive git submodules. You'll also be able to directly import modules defined in other modules.

2. Yep! This feature already exists. The field is called `reup`. (Is that helpful, or confusing?) It's mentioned in the README but only briefly. Let me know if we could document it better.

**Comment by enzochiau** [comment]
About the `reup`, I can't see you can pass the branch information to it. What I am expecting is:

1. when use `reup`, it only pull the latest of given branch. Maybe add a field in peru.yaml like:

    git module test_repo:
         url: <somepath>
         branch: devel

When run `reup`, it fetch the `devel` branch

2. Update the branch to fetch from command line:

    Before, tracking `release_v1_0` branch when doing `reup`

    Then use `reup --branch release_v2_0` to make it tracking `release_v2_0` from now on.

**Comment by oconnor663** [comment]
Define your module like this:

```
git module foo:
  url: https://github.com/foo/bar
  reup: my_branch
```

Here we're using the reup *field*, which tells the reup *command* what to do. This causes the `foo` module to look at `my_branch` to get the latest rev when you reup, instead of looking at the `master` branch.

I'm a little worried that the name `reup` is confusing when we use it for both the command and the field, even though they are related. We can't call the field `branch`, because that could get confused with the the `rev` field. (Note that the `reup` field does *not* affect what branch gets fetched by the `sync` command. That is only affected by the `rev` field, and it always defaults to `master` if the `rev` field is not set.) We could name it something more verbose, like `reup branch` or `reup source`. What do you think? @olson-sean-k?

**Comment by enzochiau** [comment]
I am not sure if you could keep both `branch` and `rev`:

When `sync`, `rev` has higher priority which if `rev` is presented, sync to that `rev`, otherwise sync to `branch` or `master` as default branch.

When `reup`, fetch to the lastest of `branch` or `master` if no `branch` is presented, update both `rev` and `branch` field.

**Comment by olson-sean-k** [comment]
> When `reup`, fetch to the lastest of `branch` or `master` if no `branch` is presented, update both `rev` and `branch` field.

I'm not sure if `peru reup` should write a `reup` field. I think omitting the field indicates that the default behavior is desired. I wouldn't expect to see that field unless a user explicitly wanted to track a particular branch (typically something other than defaults like `master`, `default`, etc.).

> What do you think?

I like the term _tracking_ for this. If we were to rename the `reup` field, I'd prefer something like `track` or `tracking` to indicate that _this is the branch that the module is tracking_. The relationship with the `peru reup` command would be a bit less obvious.

```yaml
git module libfoo:
  url: https://github.com/user/foo.git
  rev: ...
  track: unstable  # track the unstable branch
```

**Comment by oconnor663** [comment]
Suppose I have the following module (I'll use @olson-sean-k's proposed name for the field):

```
git module foo:
   url: ...
   track: release
```

I'm worried that it *really looks* like that module is going to pull from `release`. But it's not; it's going to pull from `master`. I'd like 1) a name that makes this example clear and/or 2) this example to be an error (in which case you'd be required to run `peru reup` after creating such a module, before you run `peru sync`). More thoughts?

**Comment by olson-sean-k** [comment]
> I'm worried that it _really_ looks like that module is going to pull from `release`.

Agreed, that could be misleading. Using "reup" in the field name (as your original suggestions did) should help. Something like `reup track` or `reup from`, perhaps?

```yaml
git module foo:
  url: ...
  # sync will fetch from master, but reup will get a rev from release.
  reup from: release 
```

I think this reads a bit more naturally.

**Comment by oconnor663** [comment]
I like that.

**Comment by timdp** [comment]
Git tags are also quite commonly used for versioning. How would those factor into this?

**Comment by oconnor663** [comment]
Git tags should Just Work for both `rev` and `reup`. The [git plugin](https://github.com/buildinspace/peru#creating-new-module-types) treats both of those fields as opaque strings and just passes them to commands that expect a tree-like.

**Comment by timdp** [comment]
From a semantic standpoint, `track: [tag]` doesn't make sense though. Or isn't that what you had in mind?

**Comment by oconnor663** [comment]
Yes, tags make more sense as a `rev` than as a `reup` target, though there's nothing stopping you from doing both (and in fact, nothing stopping the upstream from changing the meaning of a tag). If you're updating `rev` from one tag to another, you have to do that by hand.

If you have any ideas about reup finding new tags for you, let me know, but ultimately the mutability of tags makes me strongly prefer hashes.

**Comment by timdp** [comment]
By "finding new tags", I assume you mean detecting a version bump from the tag name? In theory, if the version number is semantic, that could work pretty well, but it seems like you'd have to make a lot of assumptions. Seems like overkill to want to accomplish this using Git.

**Comment by oconnor663** [comment]
Agreed.

**Comment by oconnor663** [comment]
@enzochiau I just pushed a scratch branch that enables nested modules: https://github.com/oconnor663/peru/tree/recursive

**Comment by oconnor663** [comment]
@enzochiau the nested projects features are in **master** now.
