### ISSUE TITLE
support a few more operations on files, to help with losing `build`

### ISSUE THREAD

**Issue by oconnor663** [buildinspace/peru#83]
Now that `build` is going/gone, the rules fields that remain are `export` and `files`. We've been talking about adding a few new fields to handle the most generic things people have been doing with `build`. I propose this set, in order of operation:

- `move`: a map of old paths to new paths
- `keep`: a replacement for `files` with a better name, though note it comes before `export`
- `executable`: a list of files to run `chmod +x` on (note that git trees only allow 644 or 755)
- `export`: same as before
- `files`: same as before, *deprecated*

It's pretty clear we want `move` to happen before anything else, especially before `export`, so that it runs while you still have all the files you started with. With that in mind, I think it makes the most sense to have *everything* happen before `export`, in the name of consistency. It would be confusing to have some fields take pre-export full paths, and others take a post-export shortened paths. The shortened paths were a bit magical anyway. This means that `keep` won't be just a renaming of `files`; it'll also take full paths instead of short paths.

Syntax-wise, `move` seems like it can only be a map of paths to paths. `keep` and `executable` can probably keep the single-glob-or-list-of-globs syntax that we currently have with `files`. It probably makes sense for executable to ignore directories, or maybe they should be an error?

@olson-sean-k also suggested a `copy` field, similar to `move` but preserving the source paths. If he wants to implement that, I have no objections :)

**Comment by oconnor663** [comment]
Sean suggested `pick` instead of `keep`. That could work.

**Comment by olson-sean-k** [comment]
Diff for `pick` field is up: https://phabricator.buildinspace.com/D180

**Comment by olson-sean-k** [comment]
Unlike the proposed operations, `copy` would generate additional data. Could that be abused when used with a recursive fetch?

**Comment by oconnor663** [comment]
I don't think we care. If you're fetching someone's repo, you're already allowing them to take as much disk space as they want.

**Comment by oconnor663** [comment]
Done! So fly.
