### ISSUE TITLE
make sure that Rule operations can't affect files outside of the project

### ISSUE THREAD

**Issue by oconnor663** [buildinspace/peru#87]
We need to watch out for `..`, absolute filepaths, and symlinks.

**Comment by olson-sean-k** [comment]
@oconnor663 suggested manipulating git trees instead of directly modifying the filesystem with `shutil` (see [d935d40936](https://github.com/buildinspace/peru/commit/d935d409366f5b7738b367057c6eee04c1e4cd1d) for example). That could help avoid bad paths/operations.

**Comment by oconnor663** [comment]
This is done!
