### ISSUE TITLE
support for authentication

### ISSUE THREAD

**Issue by questor** [buildinspace/peru#92]
if I add a private repo (hg) I have to enter the password, but I don't see any output from mercurial asking for it.... If I abort the clone I do see all output, but of course it's already to late :)

**Comment by questor** [comment]
sorry, some more comments: I'm running this on windows on the console(cmder). another thing I've noted: I don't see any messages from git or hg, even no errors....

**Comment by oconnor663** [comment]
This is a tough one. We ran into something similar at https://github.com/buildinspace/peru/issues/69. Peru's UI is designed to show fetches in parallel, so it would be difficult to allow any sort of user interaction with the fetch. Have you tried using `ssh://` and setting up certificates to authenticate automatically? ([GitHub](https://help.github.com/articles/generating-ssh-keys/), [Bitbucket](https://confluence.atlassian.com/pages/viewpage.action?pageId=270827678)) I think that should work in your case, though it'll probably be confusing if anyone else tries to sync your project without having the proper certs.

**Comment by oconnor663** [comment]
Here's [a Windows version](https://confluence.atlassian.com/display/BITBUCKET/Set+up+SSH+for+Mercurial) of those Bitbucket instructions.

**Comment by questor** [comment]
yeah, I have a workaround, but it's really strange because I don't see any output on the console (on linux I do see sync-progress).

**Comment by oconnor663** [comment]
Ah, you're probably just seeing our default output on windows, which is basically nothing. The fancy display relies on ANSI control codes that don't work on Windows, and I haven't gotten around to porting it. You can use `-v`/`--verbose` to see more stuff on Windows, but note that it has to wait for a fetch to finish before printing its output (to avoid interleaving output from multiple fetches), so you still won't see the password prompt from a hanging git command for example.

**Comment by questor** [comment]
ah, that explains a lot :) you can close the ticket if you want to create a new one regarding ansi-codes ;)

**Comment by oconnor663** [comment]
Sounds good.

**Comment by oconnor663** [comment]
https://github.com/buildinspace/peru/issues/93
