### ISSUE TITLE
Executable attributes being cleared

### ISSUE THREAD

**Issue by nikolay** [buildinspace/peru#94]
I have a zip file, which has executable files with proper flags, but Peru does not preserve the flags during copying and although the unreleased version has a rule to set the executable flag, it's not an elegant solution.

**Comment by oconnor663** [comment]
Oh good catch. I've run into this before on a totally different project. ZIP's support for file permissions is kind of nonstandard, but hopefully we handle at least whatever InfoZip does. Looks like Python is trying to fix this for 3.5: http://bugs.python.org/issue15795

**Comment by oconnor663** [comment]
Looks like the fix works by reading `external_attr`. We should be able to do the same: http://bugs.python.org/file34873/issue15795_cleaned.patch

**Comment by nikolay** [comment]
Thanks! I can't use `executable` as it's not released yet and this is blocking me from using Peru, unfortunately.

**Comment by oconnor663** [comment]
Just put up a branch for this.

**Comment by nikolay** [comment]
@oconnor663 Thank you!

**Comment by nikolay** [comment]
@oconnor663 Will this be released anytime soon along with the Python 3.4.3 fix?

**Comment by oconnor663** [comment]
We have a few larger features we're just wrapping up, so the goal is for our next release to be v0.2.0, probably by the end of the week. That's why we haven't done a bugfix release with the 3.4.3 thing.

**Comment by oconnor663** [comment]
I just submitted an updated version of my diff for this issue: https://phabricator.buildinspace.com/D198 If you want to help us review it, we can give you an account on that Phabricator server. Let us know.

**Comment by nikolay** [comment]
@oconnor663 Thanks for the honor. Unfortunately, this week I'm super busy with a big release. I can be of help after mid next week. Sorry!

**Comment by oconnor663** [comment]
Meh I just went ahead and landed it. It's got decent enough test coverage :)

**Comment by oconnor663** [comment]
Shipped.

**Comment by nikolay** [comment]
@oconnor663 Works perfectly! Thanks!

**Comment by oconnor663** [comment]
:metal:
