### ISSUE TITLE
pick doesn't work?!

### ISSUE THREAD

**Issue by questor** [buildinspace/peru#97]
I've the following config-file:
imports:
   remotery:                           extlibs/remotery
   extLibBuildfiles|remoteryBuildfile: extlibs/remotery

git module remotery:
   url: https://github.com/Celtoys/Remotery.git

hg module extLibBuildfiles:
   url: https://bitbucket.org/blubblub/extlibbuildfiles

rule remoteryBuildfile:
   pick: libRemotery.lua

I want to add an own buildfile to an already existing open source library, but calling "peru sync" results in "Unknown rule fields: pick"?!? did I make a syntax error? (currently I'm on windows and don't have a python-debugger installed, maybe tomorrow I can take a look in my linux environment)

**Comment by oconnor663** [comment]
Did you install peru using pip? The pick field works in `master`, but the latest version we've released for pip doesn't include it. Maybe I should've waited to add it to the README until it was actually shipped on PyPI...

**Comment by oconnor663** [comment]
The hope is to have version 0.2 released in the next week or two, but I'm in the middle of moving to New York, so that might get delayed.

**Comment by oconnor663** [comment]
I'm going to close this for now, though let me know if I misinterpreted your issue.

**Comment by questor** [comment]
that was a fast fix ;)

**Comment by questor** [comment]
confirmed, after downloading the sources and using this pick is working as expected...

**Comment by oconnor663** [comment]
Awesome.

**Comment by oconnor663** [comment]
Btw, 0.2 is out now on PyPI.
